spring:
  application:
    name: profileRooms
  datasource:
    url: jdbc:postgresql://localhost:5432/profileRooms
    username: postgres
    password: profile
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: M2JAJzJvcXNDLyFBNjVVZn5zLXw6Rj9HOC9OKzxnejZUXElWYiRxT0hEaDV2c29HYj4=
  expiration-time: 86400